2025-04-30 11:46:54 - INFO - Starting Federated Learning Simulation: dataset type: iid, dataset name: mnist, strategy: FedAvg(accept_failures=True), rounds: 50, clients: 20
2025-04-30 11:46:54 - WARNING - DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-04-30 11:46:54 - INFO - Starting Flower simulation, config: num_rounds=50, no round_timeout
2025-04-30 11:46:57 - INFO - Flower VCE: Ray initialized with resources: {'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 24.0, 'object_store_memory': 6185930342.0, 'node:127.0.0.1': 1.0, 'memory': 12371860686.0, 'GPU': 1.0}
2025-04-30 11:46:57 - INFO - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
2025-04-30 11:46:57 - INFO - No `client_resources` specified. Using minimal resources for clients.
2025-04-30 11:46:57 - INFO - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
2025-04-30 11:46:57 - INFO - Flower VCE: Creating VirtualClientEngineActorPool with 24 actors
2025-04-30 11:46:57 - INFO - [INIT]
2025-04-30 11:46:57 - INFO - Requesting initial parameters from one random client
2025-04-30 11:47:01 - INFO - Received initial parameters from one random client
2025-04-30 11:47:01 - INFO - Starting evaluation of initial global parameters
2025-04-30 11:47:04 - INFO - initial parameters (loss, other metrics): 0.07382761383056641, {'central_global_loss': 0.07382761383056641, 'central_global_accuracy': 0.098, 'central_clean_loss': 0.07206743800640106, 'central_clean_accuracy': 0.1215, 'central_malicious_loss': 0.07206743800640106, 'central_malicious_accuracy': 0.1215}
2025-04-30 11:47:04 - INFO - 
2025-04-30 11:47:04 - INFO - [ROUND 1]
2025-04-30 11:47:04 - INFO - configure_fit: strategy sampled 20 clients (out of 20)
2025-04-30 11:47:12 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=37092, ip=127.0.0.1, actor_id=95bccd0847650bd49aa005f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000028A00CACD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=37092, ip=127.0.0.1, actor_id=95bccd0847650bd49aa005f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000028A00CACD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

2025-04-30 11:47:12 - ERROR - [36mray::ClientAppActor.run()[39m (pid=37092, ip=127.0.0.1, actor_id=95bccd0847650bd49aa005f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000028A00CACD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=37092, ip=127.0.0.1, actor_id=95bccd0847650bd49aa005f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000028A00CACD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.
2025-04-30 11:47:12 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=13272, ip=127.0.0.1, actor_id=e5c7fa8912950d227e93328101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002196341D940>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=13272, ip=127.0.0.1, actor_id=e5c7fa8912950d227e93328101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002196341D940>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

2025-04-30 11:47:12 - ERROR - [36mray::ClientAppActor.run()[39m (pid=13272, ip=127.0.0.1, actor_id=e5c7fa8912950d227e93328101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002196341D940>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=13272, ip=127.0.0.1, actor_id=e5c7fa8912950d227e93328101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002196341D940>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.
2025-04-30 11:47:12 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=12228, ip=127.0.0.1, actor_id=604361536a88922d9b08906901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001DE0676C9A0>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12228, ip=127.0.0.1, actor_id=604361536a88922d9b08906901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001DE0676C9A0>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

2025-04-30 11:47:12 - ERROR - [36mray::ClientAppActor.run()[39m (pid=12228, ip=127.0.0.1, actor_id=604361536a88922d9b08906901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001DE0676C9A0>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12228, ip=127.0.0.1, actor_id=604361536a88922d9b08906901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001DE0676C9A0>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.
2025-04-30 11:47:12 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=40272, ip=127.0.0.1, actor_id=5d9ceb4e1e103776dcd45c5701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001CC3118C970>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=40272, ip=127.0.0.1, actor_id=5d9ceb4e1e103776dcd45c5701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001CC3118C970>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

2025-04-30 11:47:12 - ERROR - [36mray::ClientAppActor.run()[39m (pid=40272, ip=127.0.0.1, actor_id=5d9ceb4e1e103776dcd45c5701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001CC3118C970>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 114, in fit
    action = self.poisoner.select_action(state)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\attacks\deep_rl_adaptive_model_poisoning.py", line 21, in select_action
    action, _ = self.model.predict(state, deterministic=True)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\dqn\dqn.py", line 255, in predict
    action, state = self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 365, in predict
    obs_tensor, vectorized_env = self.obs_to_tensor(observation)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\policies.py", line 272, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 404, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)  # type: ignore[operator]
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\stable_baselines3\common\utils.py", line 271, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=40272, ip=127.0.0.1, actor_id=5d9ceb4e1e103776dcd45c5701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001CC3118C970>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: Error: Unexpected observation shape (10,) for Box environment, please use (5,) or (n_env, 5) for the observation shape.
2025-04-30 11:47:12 - INFO - aggregate_fit: received 16 results and 4 failures
2025-04-30 11:47:12 - WARNING - No fit_metrics_aggregation_fn provided
