2025-04-30 12:55:56 - INFO - Starting Federated Learning Simulation: dataset type: iid, dataset name: mnist, strategy: FedAvg(accept_failures=True), rounds: 50, clients: 20
2025-04-30 12:55:56 - WARNING - DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-04-30 12:55:56 - INFO - Starting Flower simulation, config: num_rounds=50, no round_timeout
2025-04-30 12:55:59 - INFO - Flower VCE: Ray initialized with resources: {'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 24.0, 'memory': 13122679604.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 6561339801.0, 'GPU': 1.0}
2025-04-30 12:55:59 - INFO - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
2025-04-30 12:55:59 - INFO - No `client_resources` specified. Using minimal resources for clients.
2025-04-30 12:55:59 - INFO - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
2025-04-30 12:55:59 - INFO - Flower VCE: Creating VirtualClientEngineActorPool with 24 actors
2025-04-30 12:55:59 - INFO - [INIT]
2025-04-30 12:55:59 - INFO - Requesting initial parameters from one random client
2025-04-30 12:56:02 - INFO - Received initial parameters from one random client
2025-04-30 12:56:02 - INFO - Starting evaluation of initial global parameters
2025-04-30 12:56:06 - INFO - initial parameters (loss, other metrics): 0.07395155334472656, {'central_global_loss': 0.07395155334472656, 'central_global_accuracy': 0.1, 'central_clean_loss': 0.07229028246402741, 'central_clean_accuracy': 0.0918, 'central_malicious_loss': 0.07229028246402741, 'central_malicious_accuracy': 0.0918}
2025-04-30 12:56:06 - INFO - 
2025-04-30 12:56:06 - INFO - [ROUND 1]
2025-04-30 12:56:06 - INFO - configure_fit: strategy sampled 20 clients (out of 20)
2025-04-30 12:56:28 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=15528, ip=127.0.0.1, actor_id=262b275479a82c6fe065983b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000020B00CACD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=15528, ip=127.0.0.1, actor_id=262b275479a82c6fe065983b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000020B00CACD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:28 - ERROR - [36mray::ClientAppActor.run()[39m (pid=15528, ip=127.0.0.1, actor_id=262b275479a82c6fe065983b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000020B00CACD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=15528, ip=127.0.0.1, actor_id=262b275479a82c6fe065983b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000020B00CACD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:28 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=12856, ip=127.0.0.1, actor_id=e58bd459093511cf54be03a701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000022E80CABD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12856, ip=127.0.0.1, actor_id=e58bd459093511cf54be03a701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000022E80CABD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:28 - ERROR - [36mray::ClientAppActor.run()[39m (pid=12856, ip=127.0.0.1, actor_id=e58bd459093511cf54be03a701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000022E80CABD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12856, ip=127.0.0.1, actor_id=e58bd459093511cf54be03a701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000022E80CABD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:28 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4796, ip=127.0.0.1, actor_id=de2daa5f26bf1ba78993e8f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000021E00CACD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4796, ip=127.0.0.1, actor_id=de2daa5f26bf1ba78993e8f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000021E00CACD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:28 - ERROR - [36mray::ClientAppActor.run()[39m (pid=4796, ip=127.0.0.1, actor_id=de2daa5f26bf1ba78993e8f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000021E00CACD90>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4796, ip=127.0.0.1, actor_id=de2daa5f26bf1ba78993e8f901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x0000021E00CACD90>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:28 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:28 - ERROR - [36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:28 - INFO - aggregate_fit: received 16 results and 4 failures
2025-04-30 12:56:28 - WARNING - No fit_metrics_aggregation_fn provided
2025-04-30 12:56:31 - INFO - fit progress: (1, 0.008390912652015687, {'central_global_loss': 0.008390912652015687, 'central_global_accuracy': 0.938, 'central_clean_loss': 0.007817853787168861, 'central_clean_accuracy': 0.9329, 'central_malicious_loss': 0.007817853787168861, 'central_malicious_accuracy': 0.9329}, 25.0543384)
2025-04-30 12:56:31 - INFO - configure_evaluate: strategy sampled 20 clients (out of 20)
2025-04-30 12:56:32 - INFO - aggregate_evaluate: received 20 results and 0 failures
2025-04-30 12:56:32 - INFO - 
2025-04-30 12:56:32 - INFO - [ROUND 2]
2025-04-30 12:56:32 - INFO - configure_fit: strategy sampled 20 clients (out of 20)
2025-04-30 12:56:50 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=15192, ip=127.0.0.1, actor_id=d2ae0a233c1ba4d9f2dc9bb201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000265A872C940>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=15192, ip=127.0.0.1, actor_id=d2ae0a233c1ba4d9f2dc9bb201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000265A872C940>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:50 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:50 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=17748, ip=127.0.0.1, actor_id=0865746dbfb96e83ff45c28901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002188E79B9A0>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=17748, ip=127.0.0.1, actor_id=0865746dbfb96e83ff45c28901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002188E79B9A0>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:50 - ERROR - Traceback (most recent call last):
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=26516, ip=127.0.0.1, actor_id=89163d09174e97d9284a3f2701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002092EF8B6D0>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=26516, ip=127.0.0.1, actor_id=89163d09174e97d9284a3f2701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002092EF8B6D0>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

2025-04-30 12:56:50 - ERROR - [36mray::ClientAppActor.run()[39m (pid=15192, ip=127.0.0.1, actor_id=d2ae0a233c1ba4d9f2dc9bb201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000265A872C940>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=15192, ip=127.0.0.1, actor_id=d2ae0a233c1ba4d9f2dc9bb201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000265A872C940>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:55 - ERROR - [36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=32252, ip=127.0.0.1, actor_id=1eca2d778bae158de128a66701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001E04A79C970>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:55 - ERROR - [36mray::ClientAppActor.run()[39m (pid=17748, ip=127.0.0.1, actor_id=0865746dbfb96e83ff45c28901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002188E79B9A0>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=17748, ip=127.0.0.1, actor_id=0865746dbfb96e83ff45c28901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002188E79B9A0>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
2025-04-30 12:56:55 - ERROR - [36mray::ClientAppActor.run()[39m (pid=26516, ip=127.0.0.1, actor_id=89163d09174e97d9284a3f2701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002092EF8B6D0>)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\client\numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\RL Adaptive Model Poisoning Attacks in FL\federated_learning\poisoned_client.py", line 153, in fit
    self.poisoner.decay()
AttributeError: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=26516, ip=127.0.0.1, actor_id=89163d09174e97d9284a3f2701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000002092EF8B6D0>)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\RL Adaptive Model Poisoning Attacks in FL\.venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'RLAdaptiveModelPoisoning' object has no attribute 'decay'
